POST http://localhost/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "NewUser",
    "email": "newUser@mail.loc",
    "password": "Secret123",
    "password_confirmation": "Secret123"
}
